# Custom configuration for cell classification
# This demonstrates how to override specific settings from the default config

# Import base configuration
_base_: "default.yaml"

# Override specific settings
common:
  gpu: 1  # Use different GPU

data:
  dataset: "HiCervix"  # Change dataset (see default.yaml for all available options)

backbone:
  name: "SigLIP"  # Change backbone model (see default.yaml for all available options)

training:
  batch_size: 32  # Smaller batch size
  epochs: 100     # More epochs
  lr: 0.0005      # Different learning rate

evaluation:
  compute_ci: false  # Disable confidence intervals for faster evaluation