# Example configuration showing different dataset and backbone combinations
# This demonstrates how to modify the default config for different experiments

# Import base configuration
_base_: "default.yaml"
common:
  gpu: 0
# Example 1: Use HiCervix dataset with CLIP backbone
data:
  dataset: "Herlev"  # Change from default Herlev to HiCervix

backbone:
  name: "ResNet50"  # Change from default ResNet50 to CLIP
  freeze: false  # Keep backbone frozen for linear probing

training:
  epochs: 50  # Increase epochs for better convergence
  lr: 0.0005   # Lower learning rate for CLIP

# Example configurations for other combinations:
# 
# For SigLIP backbone with SIPaKMeD dataset:
# data:
#   dataset: "SIPaKMeD"
# backbone:
#   name: "SigLIP"
#
# For fine-tuning (unfrozen backbone):
# backbone:
#   name: "SigLIP2-ViT-L"
#   freeze: false
# training:
#   lr: 0.00001  # Much lower learning rate for fine-tuning
#
# For quick testing:
# training:
#   epochs: 5
#   batch_size: 32
# evaluation:
#   compute_ci: false
